### ISSUE TITLE
cannot import name 'PyAsn1UnicodeDecodeError'

### ISSUE THREAD

**Issue by suganesh2020** [kanayak123/pyadselfservice#12]
i have install pyadselfservice with following link
 http://technokan.blogspot.com/2016/10/web-based-python3-password-reset-tool.html
 i am getting error like below  kindly advice 

Environment:

Request Method: GET
Request URL: http://pyadselfservice.XXXXX.com/

Django Version: 3.0.4
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'validateuser',
 'nocaptcha_recaptcha',
 'zxcvbn_password']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    <source code not available>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    <source code not available>
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    <source code not available>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    <source code not available>
  File "/opt/pyadselfservice/pyadselfservice/pyadselfservice/urls.py", line 33, in <module>
    from validateuser import views
  File "/opt/pyadselfservice/pyadselfservice/validateuser/views.py", line 25, in <module>
    from .adpassreset import do_validate, do_reset, calc_base32
  File "/opt/pyadselfservice/pyadselfservice/validateuser/adpassreset.py", line 11, in <module>
    import ldap3, sys, getpass, logging, time, ssl, re
  File "/usr/local/lib/python3.6/dist-packages/ldap3/__init__.py", line 139, in <module>
    from .core.connection import Connection
  File "/usr/local/lib/python3.6/dist-packages/ldap3/core/connection.py", line 44, in <module>
    from ..operation.compare import compare_operation, compare_request_to_dict
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/compare.py", line 28, in <module>
    from ..operation.search import ava_to_dict
  File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 41, in <module>
    from pyasn1.error import PyAsn1UnicodeDecodeError

Exception Type: ImportError at /
Exception Value: cannot import name 'PyAsn1UnicodeDecodeError'

**Comment by kanayak123** [comment]
Sorry about the delay.. did it work or you stopped exploring this tool?

**Comment by kanayak123** [comment]
Check out the new version, fixed codes and upgraded the compatibility with Django 5.0
